//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_display.SR_FMD {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pack", Namespace="http://schemas.datacontract.org/2004/07/FMD.DTO")]
    [System.SerializableAttribute()]
    public partial class Pack : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string batchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string expiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productCodeSchemeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string serialNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string batchId {
            get {
                return this.batchIdField;
            }
            set {
                if ((object.ReferenceEquals(this.batchIdField, value) != true)) {
                    this.batchIdField = value;
                    this.RaisePropertyChanged("batchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.expiryDateField, value) != true)) {
                    this.expiryDateField = value;
                    this.RaisePropertyChanged("expiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.productCodeField, value) != true)) {
                    this.productCodeField = value;
                    this.RaisePropertyChanged("productCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productCodeScheme {
            get {
                return this.productCodeSchemeField;
            }
            set {
                if ((object.ReferenceEquals(this.productCodeSchemeField, value) != true)) {
                    this.productCodeSchemeField = value;
                    this.RaisePropertyChanged("productCodeScheme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string serialNumber {
            get {
                return this.serialNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.serialNumberField, value) != true)) {
                    this.serialNumberField = value;
                    this.RaisePropertyChanged("serialNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/FMD.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POS_display.SR_FMD.BulkOfPacksResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POS_display.SR_FMD.LocationResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POS_display.SR_FMD.APIresponse))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string informationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jsonRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jsonResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string information {
            get {
                return this.informationField;
            }
            set {
                if ((object.ReferenceEquals(this.informationField, value) != true)) {
                    this.informationField = value;
                    this.RaisePropertyChanged("information");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jsonRequest {
            get {
                return this.jsonRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.jsonRequestField, value) != true)) {
                    this.jsonRequestField = value;
                    this.RaisePropertyChanged("jsonRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jsonResponse {
            get {
                return this.jsonResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.jsonResponseField, value) != true)) {
                    this.jsonResponseField = value;
                    this.RaisePropertyChanged("jsonResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkOfPacksResponse", Namespace="http://schemas.datacontract.org/2004/07/FMD.DTO")]
    [System.SerializableAttribute()]
    public partial class BulkOfPacksResponse : POS_display.SR_FMD.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime etaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime expiresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operationCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime eta {
            get {
                return this.etaField;
            }
            set {
                if ((this.etaField.Equals(value) != true)) {
                    this.etaField = value;
                    this.RaisePropertyChanged("eta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expires {
            get {
                return this.expiresField;
            }
            set {
                if ((this.expiresField.Equals(value) != true)) {
                    this.expiresField = value;
                    this.RaisePropertyChanged("expires");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.operationCodeField, value) != true)) {
                    this.operationCodeField = value;
                    this.RaisePropertyChanged("operationCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationResponse", Namespace="http://schemas.datacontract.org/2004/07/FMD.DTO")]
    [System.SerializableAttribute()]
    public partial class LocationResponse : POS_display.SR_FMD.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POS_display.SR_FMD.Data[] packsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.operationCodeField, value) != true)) {
                    this.operationCodeField = value;
                    this.RaisePropertyChanged("operationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public POS_display.SR_FMD.Data[] packs {
            get {
                return this.packsField;
            }
            set {
                if ((object.ReferenceEquals(this.packsField, value) != true)) {
                    this.packsField = value;
                    this.RaisePropertyChanged("packs");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APIresponse", Namespace="http://schemas.datacontract.org/2004/07/FMD.DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POS_display.SR_FMD.SinglePackResponse))]
    public partial class APIresponse : POS_display.SR_FMD.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string stateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state {
            get {
                return this.stateField;
            }
            set {
                if ((object.ReferenceEquals(this.stateField, value) != true)) {
                    this.stateField = value;
                    this.RaisePropertyChanged("state");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SinglePackResponse", Namespace="http://schemas.datacontract.org/2004/07/FMD.DTO")]
    [System.SerializableAttribute()]
    public partial class SinglePackResponse : POS_display.SR_FMD.APIresponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string alertIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string operationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string warningField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alertId {
            get {
                return this.alertIdField;
            }
            set {
                if ((object.ReferenceEquals(this.alertIdField, value) != true)) {
                    this.alertIdField = value;
                    this.RaisePropertyChanged("alertId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operationCode {
            get {
                return this.operationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.operationCodeField, value) != true)) {
                    this.operationCodeField = value;
                    this.RaisePropertyChanged("operationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string warning {
            get {
                return this.warningField;
            }
            set {
                if ((object.ReferenceEquals(this.warningField, value) != true)) {
                    this.warningField = value;
                    this.RaisePropertyChanged("warning");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://schemas.datacontract.org/2004/07/FMD.DTO")]
    [System.SerializableAttribute()]
    public partial class Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POS_display.SR_FMD.Pack packField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POS_display.SR_FMD.SinglePackResponse resultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public POS_display.SR_FMD.Pack pack {
            get {
                return this.packField;
            }
            set {
                if ((object.ReferenceEquals(this.packField, value) != true)) {
                    this.packField = value;
                    this.RaisePropertyChanged("pack");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public POS_display.SR_FMD.SinglePackResponse result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="State", Namespace="http://schemas.datacontract.org/2004/07/FMD.DTO")]
    public enum State : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Active = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Supplied = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exported = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Stolen = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sample = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FreeSample = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Locked = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Destroyed = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Recalled = 8,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_FMD.IServiceFMD")]
    public interface IServiceFMD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/VerifySinglePack", ReplyAction="http://tempuri.org/IServiceFMD/VerifySinglePackResponse")]
        POS_display.SR_FMD.APIresponse VerifySinglePack(string endpointId, POS_display.SR_FMD.Pack pack, bool IsManualEntry, decimal localTransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/VerifySinglePack", ReplyAction="http://tempuri.org/IServiceFMD/VerifySinglePackResponse")]
        System.Threading.Tasks.Task<POS_display.SR_FMD.APIresponse> VerifySinglePackAsync(string endpointId, POS_display.SR_FMD.Pack pack, bool IsManualEntry, decimal localTransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/ChangeStateSinglePack", ReplyAction="http://tempuri.org/IServiceFMD/ChangeStateSinglePackResponse")]
        POS_display.SR_FMD.APIresponse ChangeStateSinglePack(string endpointId, POS_display.SR_FMD.Pack pack, bool IsManualEntry, POS_display.SR_FMD.State state, System.Nullable<decimal> localTransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/ChangeStateSinglePack", ReplyAction="http://tempuri.org/IServiceFMD/ChangeStateSinglePackResponse")]
        System.Threading.Tasks.Task<POS_display.SR_FMD.APIresponse> ChangeStateSinglePackAsync(string endpointId, POS_display.SR_FMD.Pack pack, bool IsManualEntry, POS_display.SR_FMD.State state, System.Nullable<decimal> localTransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/VerifyBulkOfPacks", ReplyAction="http://tempuri.org/IServiceFMD/VerifyBulkOfPacksResponse")]
        POS_display.SR_FMD.BulkOfPacksResponse VerifyBulkOfPacks(string endpointId, POS_display.SR_FMD.Pack[] packs, decimal localTransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/VerifyBulkOfPacks", ReplyAction="http://tempuri.org/IServiceFMD/VerifyBulkOfPacksResponse")]
        System.Threading.Tasks.Task<POS_display.SR_FMD.BulkOfPacksResponse> VerifyBulkOfPacksAsync(string endpointId, POS_display.SR_FMD.Pack[] packs, decimal localTransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/ChangeStateBulkOfPacks", ReplyAction="http://tempuri.org/IServiceFMD/ChangeStateBulkOfPacksResponse")]
        POS_display.SR_FMD.BulkOfPacksResponse ChangeStateBulkOfPacks(string endpointId, POS_display.SR_FMD.Pack[] packs, POS_display.SR_FMD.State state, decimal localTransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/ChangeStateBulkOfPacks", ReplyAction="http://tempuri.org/IServiceFMD/ChangeStateBulkOfPacksResponse")]
        System.Threading.Tasks.Task<POS_display.SR_FMD.BulkOfPacksResponse> ChangeStateBulkOfPacksAsync(string endpointId, POS_display.SR_FMD.Pack[] packs, POS_display.SR_FMD.State state, decimal localTransId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/ResponseBulkOfPacks", ReplyAction="http://tempuri.org/IServiceFMD/ResponseBulkOfPacksResponse")]
        bool ResponseBulkOfPacks(string endpointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/ResponseBulkOfPacks", ReplyAction="http://tempuri.org/IServiceFMD/ResponseBulkOfPacksResponse")]
        System.Threading.Tasks.Task<bool> ResponseBulkOfPacksAsync(string endpointId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/ResponseBulkOfPacksById", ReplyAction="http://tempuri.org/IServiceFMD/ResponseBulkOfPacksByIdResponse")]
        POS_display.SR_FMD.LocationResponse ResponseBulkOfPacksById(string endpointId, decimal bulkOfPacksId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceFMD/ResponseBulkOfPacksById", ReplyAction="http://tempuri.org/IServiceFMD/ResponseBulkOfPacksByIdResponse")]
        System.Threading.Tasks.Task<POS_display.SR_FMD.LocationResponse> ResponseBulkOfPacksByIdAsync(string endpointId, decimal bulkOfPacksId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceFMDChannel : POS_display.SR_FMD.IServiceFMD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceFMDClient : System.ServiceModel.ClientBase<POS_display.SR_FMD.IServiceFMD>, POS_display.SR_FMD.IServiceFMD {
        
        public ServiceFMDClient() {
        }
        
        public ServiceFMDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceFMDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFMDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceFMDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public POS_display.SR_FMD.APIresponse VerifySinglePack(string endpointId, POS_display.SR_FMD.Pack pack, bool IsManualEntry, decimal localTransId) {
            return base.Channel.VerifySinglePack(endpointId, pack, IsManualEntry, localTransId);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_FMD.APIresponse> VerifySinglePackAsync(string endpointId, POS_display.SR_FMD.Pack pack, bool IsManualEntry, decimal localTransId) {
            return base.Channel.VerifySinglePackAsync(endpointId, pack, IsManualEntry, localTransId);
        }
        
        public POS_display.SR_FMD.APIresponse ChangeStateSinglePack(string endpointId, POS_display.SR_FMD.Pack pack, bool IsManualEntry, POS_display.SR_FMD.State state, System.Nullable<decimal> localTransId) {
            return base.Channel.ChangeStateSinglePack(endpointId, pack, IsManualEntry, state, localTransId);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_FMD.APIresponse> ChangeStateSinglePackAsync(string endpointId, POS_display.SR_FMD.Pack pack, bool IsManualEntry, POS_display.SR_FMD.State state, System.Nullable<decimal> localTransId) {
            return base.Channel.ChangeStateSinglePackAsync(endpointId, pack, IsManualEntry, state, localTransId);
        }
        
        public POS_display.SR_FMD.BulkOfPacksResponse VerifyBulkOfPacks(string endpointId, POS_display.SR_FMD.Pack[] packs, decimal localTransId) {
            return base.Channel.VerifyBulkOfPacks(endpointId, packs, localTransId);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_FMD.BulkOfPacksResponse> VerifyBulkOfPacksAsync(string endpointId, POS_display.SR_FMD.Pack[] packs, decimal localTransId) {
            return base.Channel.VerifyBulkOfPacksAsync(endpointId, packs, localTransId);
        }
        
        public POS_display.SR_FMD.BulkOfPacksResponse ChangeStateBulkOfPacks(string endpointId, POS_display.SR_FMD.Pack[] packs, POS_display.SR_FMD.State state, decimal localTransId) {
            return base.Channel.ChangeStateBulkOfPacks(endpointId, packs, state, localTransId);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_FMD.BulkOfPacksResponse> ChangeStateBulkOfPacksAsync(string endpointId, POS_display.SR_FMD.Pack[] packs, POS_display.SR_FMD.State state, decimal localTransId) {
            return base.Channel.ChangeStateBulkOfPacksAsync(endpointId, packs, state, localTransId);
        }
        
        public bool ResponseBulkOfPacks(string endpointId) {
            return base.Channel.ResponseBulkOfPacks(endpointId);
        }
        
        public System.Threading.Tasks.Task<bool> ResponseBulkOfPacksAsync(string endpointId) {
            return base.Channel.ResponseBulkOfPacksAsync(endpointId);
        }
        
        public POS_display.SR_FMD.LocationResponse ResponseBulkOfPacksById(string endpointId, decimal bulkOfPacksId) {
            return base.Channel.ResponseBulkOfPacksById(endpointId, bulkOfPacksId);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_FMD.LocationResponse> ResponseBulkOfPacksByIdAsync(string endpointId, decimal bulkOfPacksId) {
            return base.Channel.ResponseBulkOfPacksByIdAsync(endpointId, bulkOfPacksId);
        }
    }
}
