//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_display.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POS_display.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///	&lt;Modulus&gt;xZUo0Yz7xI3WHD3QH6K3ERqDM09N6mCUlJzRt9c5oRaY2veWkAouAOfHvs5VGIiO/3SAJndu+gHcniNdXVBdxW4CQUzfTCYrreBQLDb0UEmgjNKkHGMxgfo3LU3N2A3LdROLaoJTAA0yqojgiLsh+nOf3Cq0e9EvMNoLx97JQ3k=&lt;/Modulus&gt;
        ///	&lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///	&lt;D&gt;rK4g/4uE2pLPpt0LESsHbgZK1kQgJ5ADKyMnUtHiRvxV2UF7sCWFcTsg4oy36Hoo5/Ass/G75vpLk1X7GjvLxuBH7xVMQKkFgchRccpSUKwyoMVO6K87IQwxSpG7CLbqJfKm8TouRDXRrevLusPaeuEbyk87VH4esY9SW94/slE=&lt;/D&gt;
        ///	&lt;P&gt;62aPVXNsTA/xZ4PExp9JQxj0k92PdIrIphLlDgvRs3dwZThWwr5mhA24r99O+F+ZHqedzcC2vbmm8xChu1kVVQ==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _124807124 {
            get {
                return ResourceManager.GetString("_124807124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///	&lt;Modulus&gt;2wOF6pzuUkcEjQFZ33bpqMrJnd01WHmIoHwUtrHszKjQ3yCSjwkOddNbEbhggFYEV6B6DZJJ1vH3IuX2a9EXiTAa0VUycMHVtOTdT0CgXI14lm2r4KMLBxLhbCsLZHjhzYQhQ8JYK+iCfxHvISJ8aylGiaBt6M0Y8nxR48XTKr8=&lt;/Modulus&gt;
        ///	&lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///	&lt;D&gt;ZT6DsalKIo7h860kNsFp0rWr7mZMOtIz7rxtdudZaGLB6+PK3IR7Qsyp1M8/DRS2fSuaQJvXtp20eVWFTOIj1lSG5rStd7Og8aNgVtEymO3JyB1OiODObHr7KKsWAVDAt0l4PpiS0hsxS73dl0XNNSw2vd+FdSO217NFn9lQDYE=&lt;/D&gt;
        ///	&lt;P&gt;8Z1y/mFMNHXKdtqS9vt8sRnjJny7N+3UoTwGja/lX8huEBeWV6P+ZeCZ3O5vjv2qtsOQ9GaGAdcQoaCXUzkgFw==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _135060830 {
            get {
                return ResourceManager.GetString("_135060830", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///	&lt;Modulus&gt;txub+DmS6oEzzwVsQNoc5Gw+8oANiwSitMElvIdg6hosjB97F3+1Qrtxy7mVrs6htLfFpcjdnT4usFBShsLET5q/+eUrL6VBsyR/5VohILv0VXcvFhBqqwp/ZuH/sXhal2XEbUSKxYXxItH7klK7qI+REC5l3sqqnTOTuMfcUVk=&lt;/Modulus&gt;
        ///	&lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///	&lt;D&gt;jL+kPEHFNIzsDg3VEGSYIN0z5aOYxWtixh5Rq4FEda5435yzOXTpF8qNxlN5Q02B7y/ztWOZNe0+ZjjXts6vplLPTjhfJj9rckPRWWpGmK3l4tIM6sz+Avx23/V5VnjByfP1YA2R9zAFuw/4NHe06wrMK7jF0ggouuJkdylKKoE=&lt;/D&gt;
        ///	&lt;P&gt;7QHwswkJVW9eV9GCEXrJ2q02O9EkjNmJtA5AmaHG64mlaXSF03myJlfOSicotjK1W/nhtISJ+0VaH9EGjkvyjQ==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _135874035 {
            get {
                return ResourceManager.GetString("_135874035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///	&lt;Modulus&gt;o4K7ptGsfo90sQkttgcjtLfEWJSvCyralZ39xr5lxM0d0tcnWEe4GuMspY1Lv4GI/EjojKRRmXjmckLmfj/OOQswkX3iJ14/7xrvfk7J12QBzNq+uUGeIijoBTfUo14mmpZXtCIR4cpCxVW2GyEamtmHkyboBlDDcs4EN+pyK1U=&lt;/Modulus&gt;
        ///	&lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///	&lt;D&gt;bj3EezK+1A2wpXQEx8eEgWGtFfQZGLRp75o38fmI7+lDhFXfhxvDuw0TmwLq4VFapI4bjEd1ZL4o0Tzd3pzyUlud7ZH5IaEOUWY+/W0oZOy26EI63MExqXHNlMr4khlaThyYvyNg5R4w8crym7oY47Vt1MeVfuW3X3WX0JJivUE=&lt;/D&gt;
        ///	&lt;P&gt;zlhmvgdwtxyIxiMsbFiFbtseboUrNnVCsEacA23D6QmCMMXMvxWa60TrZiRWHwraJemaL1G2kEWMe0KwqNcWuQ==&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _303364097 {
            get {
                return ResourceManager.GetString("_303364097", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;RSAKeyValue&gt;
        ///	&lt;Modulus&gt;ochPB5rb8TWnocqLF7OEZtYgN20/41ohX7L1eq3A+ReciCS56EPUbvNZkyjb0nhE3dK1zY4r+8CdBsqXPEOXjUJ/HyjnetR/puVRO5FzlXnwI7TtW0EOe9Lt+rjHmzKyviMlA558fCnx2VpfiMd/NzY4OQLPhau5/dKR7CPG44s=&lt;/Modulus&gt;
        ///	&lt;Exponent&gt;AQAB&lt;/Exponent&gt;
        ///	&lt;P&gt;1AfLEvLqNveGuolcLcSd9pQSbulC+GNkzJidXSV1J07wP0DpVJ2fBgclJvNrjXrCLb2P8pedCnvrFjJKrit72w==&lt;/P&gt;
        ///	&lt;Q&gt;w1T3QThg7c0ixQhucgFHoP1RDkbQksWxcQ5oytsrE56E+pUugCo9RxbcBDvCqtXlnmjl35w4KbRg5xCxrSAeEQ==&lt;/Q&gt;
        ///	&lt;DP&gt;lJl9pqMeqTVjdFqOgvkYqFbwcFEFAaZPX+DZ8Q0uhUUatYodvZLWf9gEHr9dMoPFkV8YgrHlex [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _307071729 {
            get {
                return ResourceManager.GetString("_307071729", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap barcode {
            get {
                object obj = ResourceManager.GetObject("barcode", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BENU {
            get {
                object obj = ResourceManager.GetObject("BENU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BENU_logo {
            get {
                object obj = ResourceManager.GetObject("BENU_logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to $DB_CONF[66][&quot;name&quot;]     = &quot;Vaistinė&quot;;
        ///$DB_CONF[66][&quot;database&quot;] = &quot;kas&quot;;
        ///$DB_CONF[66][&quot;user&quot;]     = &quot;kas&quot;;
        ///$DB_CONF[66][&quot;password&quot;] = &quot;llopasss&quot;;.
        /// </summary>
        public static string db_conf {
            get {
                return ResourceManager.GetString("db_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] DejaVuSansCondensed {
            get {
                object obj = ResourceManager.GetObject("DejaVuSansCondensed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon donations {
            get {
                object obj = ResourceManager.GetObject("donations", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap filter {
            get {
                object obj = ResourceManager.GetObject("filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fonas {
            get {
                object obj = ResourceManager.GetObject("Fonas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fonas_vertical {
            get {
                object obj = ResourceManager.GetObject("Fonas_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap GYDYTOJO {
            get {
                object obj = ResourceManager.GetObject("GYDYTOJO", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap magstripe {
            get {
                object obj = ResourceManager.GetObject("magstripe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap RIMI {
            get {
                object obj = ResourceManager.GetObject("RIMI", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stop {
            get {
                object obj = ResourceManager.GetObject("stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap unlock {
            get {
                object obj = ResourceManager.GetObject("unlock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
