//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_display.SR_Privat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Obj", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POS_display.SR_Privat.Transaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(POS_display.SR_Privat.Account))]
    public partial class Obj : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrCode {
            get {
                return this.ErrCodeField;
            }
            set {
                if ((this.ErrCodeField.Equals(value) != true)) {
                    this.ErrCodeField = value;
                    this.RaisePropertyChanged("ErrCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Err {
            get {
                return this.ErrField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrField, value) != true)) {
                    this.ErrField = value;
                    this.RaisePropertyChanged("Err");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaction", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Transaction : POS_display.SR_Privat.Obj {
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POS_display.SR_Privat.Account AccField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public POS_display.SR_Privat.Account Acc {
            get {
                return this.AccField;
            }
            set {
                if ((object.ReferenceEquals(this.AccField, value) != true)) {
                    this.AccField = value;
                    this.RaisePropertyChanged("Acc");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Account : POS_display.SR_Privat.Obj {
        
        private int CardIdField;
        
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNameField;
        
        private int AccountTypeField;
        
        private double CurrentBalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private int IsValidField;
        
        private int CreditOnlyField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CardId {
            get {
                return this.CardIdField;
            }
            set {
                if ((this.CardIdField.Equals(value) != true)) {
                    this.CardIdField = value;
                    this.RaisePropertyChanged("CardId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AccountName {
            get {
                return this.AccountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNameField, value) != true)) {
                    this.AccountNameField = value;
                    this.RaisePropertyChanged("AccountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double CurrentBalance {
            get {
                return this.CurrentBalanceField;
            }
            set {
                if ((this.CurrentBalanceField.Equals(value) != true)) {
                    this.CurrentBalanceField = value;
                    this.RaisePropertyChanged("CurrentBalance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int IsValid {
            get {
                return this.IsValidField;
            }
            set {
                if ((this.IsValidField.Equals(value) != true)) {
                    this.IsValidField = value;
                    this.RaisePropertyChanged("IsValid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int CreditOnly {
            get {
                return this.CreditOnlyField;
            }
            set {
                if ((this.CreditOnlyField.Equals(value) != true)) {
                    this.CreditOnlyField = value;
                    this.RaisePropertyChanged("CreditOnly");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Items", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Items : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<POS_display.SR_Privat.Item> ItField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<POS_display.SR_Privat.Item> It {
            get {
                return this.ItField;
            }
            set {
                if ((object.ReferenceEquals(this.ItField, value) != true)) {
                    this.ItField = value;
                    this.RaisePropertyChanged("It");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal PosdIdField;
        
        private decimal ProductIdField;
        
        private double SumField;
        
        private double QtyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal PosdId {
            get {
                return this.PosdIdField;
            }
            set {
                if ((this.PosdIdField.Equals(value) != true)) {
                    this.PosdIdField = value;
                    this.RaisePropertyChanged("PosdId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double Qty {
            get {
                return this.QtyField;
            }
            set {
                if ((this.QtyField.Equals(value) != true)) {
                    this.QtyField = value;
                    this.RaisePropertyChanged("Qty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_Privat.PrivatSoap")]
    public interface PrivatSoap {
        
        // CODEGEN: Generating message contract since element name cardNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAccount", ReplyAction="*")]
        POS_display.SR_Privat.GetAccountResponse GetAccount(POS_display.SR_Privat.GetAccountRequest request);
        
        // CODEGEN: Generating message contract since element name cardNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTransaction", ReplyAction="*")]
        POS_display.SR_Privat.CreateTransactionResponse CreateTransaction(POS_display.SR_Privat.CreateTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VoidTransaction", ReplyAction="*")]
        bool VoidTransaction(int pharmac_ID, decimal posh_ID, bool production);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccount", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_Privat.GetAccountRequestBody Body;
        
        public GetAccountRequest() {
        }
        
        public GetAccountRequest(POS_display.SR_Privat.GetAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal pharmac_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool production;
        
        public GetAccountRequestBody() {
        }
        
        public GetAccountRequestBody(string cardNo, decimal pharmac_id, System.DateTime date, bool production) {
            this.cardNo = cardNo;
            this.pharmac_id = pharmac_id;
            this.date = date;
            this.production = production;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_Privat.GetAccountResponseBody Body;
        
        public GetAccountResponse() {
        }
        
        public GetAccountResponse(POS_display.SR_Privat.GetAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POS_display.SR_Privat.Account GetAccountResult;
        
        public GetAccountResponseBody() {
        }
        
        public GetAccountResponseBody(POS_display.SR_Privat.Account GetAccountResult) {
            this.GetAccountResult = GetAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTransaction", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_Privat.CreateTransactionRequestBody Body;
        
        public CreateTransactionRequest() {
        }
        
        public CreateTransactionRequest(POS_display.SR_Privat.CreateTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime date;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double sum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal pharmac_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int reason_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int status;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double sum2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal posh_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public POS_display.SR_Privat.Items items;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool production;
        
        public CreateTransactionRequestBody() {
        }
        
        public CreateTransactionRequestBody(string cardNo, System.DateTime date, double sum, decimal pharmac_id, int reason_code, int status, double sum2, decimal posh_id, POS_display.SR_Privat.Items items, bool production) {
            this.cardNo = cardNo;
            this.date = date;
            this.sum = sum;
            this.pharmac_id = pharmac_id;
            this.reason_code = reason_code;
            this.status = status;
            this.sum2 = sum2;
            this.posh_id = posh_id;
            this.items = items;
            this.production = production;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_Privat.CreateTransactionResponseBody Body;
        
        public CreateTransactionResponse() {
        }
        
        public CreateTransactionResponse(POS_display.SR_Privat.CreateTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POS_display.SR_Privat.Transaction CreateTransactionResult;
        
        public CreateTransactionResponseBody() {
        }
        
        public CreateTransactionResponseBody(POS_display.SR_Privat.Transaction CreateTransactionResult) {
            this.CreateTransactionResult = CreateTransactionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PrivatSoapChannel : POS_display.SR_Privat.PrivatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PrivatSoapClient : System.ServiceModel.ClientBase<POS_display.SR_Privat.PrivatSoap>, POS_display.SR_Privat.PrivatSoap {
        
        public PrivatSoapClient() {
        }
        
        public PrivatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PrivatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrivatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PrivatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_Privat.GetAccountResponse POS_display.SR_Privat.PrivatSoap.GetAccount(POS_display.SR_Privat.GetAccountRequest request) {
            return base.Channel.GetAccount(request);
        }
        
        public POS_display.SR_Privat.Account GetAccount(string cardNo, decimal pharmac_id, System.DateTime date, bool production) {
            POS_display.SR_Privat.GetAccountRequest inValue = new POS_display.SR_Privat.GetAccountRequest();
            inValue.Body = new POS_display.SR_Privat.GetAccountRequestBody();
            inValue.Body.cardNo = cardNo;
            inValue.Body.pharmac_id = pharmac_id;
            inValue.Body.date = date;
            inValue.Body.production = production;
            POS_display.SR_Privat.GetAccountResponse retVal = ((POS_display.SR_Privat.PrivatSoap)(this)).GetAccount(inValue);
            return retVal.Body.GetAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_Privat.CreateTransactionResponse POS_display.SR_Privat.PrivatSoap.CreateTransaction(POS_display.SR_Privat.CreateTransactionRequest request) {
            return base.Channel.CreateTransaction(request);
        }
        
        public POS_display.SR_Privat.Transaction CreateTransaction(string cardNo, System.DateTime date, double sum, decimal pharmac_id, int reason_code, int status, double sum2, decimal posh_id, POS_display.SR_Privat.Items items, bool production) {
            POS_display.SR_Privat.CreateTransactionRequest inValue = new POS_display.SR_Privat.CreateTransactionRequest();
            inValue.Body = new POS_display.SR_Privat.CreateTransactionRequestBody();
            inValue.Body.cardNo = cardNo;
            inValue.Body.date = date;
            inValue.Body.sum = sum;
            inValue.Body.pharmac_id = pharmac_id;
            inValue.Body.reason_code = reason_code;
            inValue.Body.status = status;
            inValue.Body.sum2 = sum2;
            inValue.Body.posh_id = posh_id;
            inValue.Body.items = items;
            inValue.Body.production = production;
            POS_display.SR_Privat.CreateTransactionResponse retVal = ((POS_display.SR_Privat.PrivatSoap)(this)).CreateTransaction(inValue);
            return retVal.Body.CreateTransactionResult;
        }
        
        public bool VoidTransaction(int pharmac_ID, decimal posh_ID, bool production) {
            return base.Channel.VoidTransaction(pharmac_ID, posh_ID, production);
        }
    }
}
