//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_display.SR_DrugNotes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_DrugNotes.DrugNotesWSSoap")]
    public interface DrugNotesWSSoap {
        
        // CODEGEN: Generating message contract since element name VID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugNotesByProductVID", ReplyAction="*")]
        POS_display.SR_DrugNotes.GetDrugNotesByProductVIDResponse GetDrugNotesByProductVID(POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugNotesByProductVID", ReplyAction="*")]
        System.Threading.Tasks.Task<POS_display.SR_DrugNotes.GetDrugNotesByProductVIDResponse> GetDrugNotesByProductVIDAsync(POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetDrugNotesByProductIDResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugNotesByProductID", ReplyAction="*")]
        POS_display.SR_DrugNotes.GetDrugNotesByProductIDResponse GetDrugNotesByProductID(POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDrugNotesByProductID", ReplyAction="*")]
        System.Threading.Tasks.Task<POS_display.SR_DrugNotes.GetDrugNotesByProductIDResponse> GetDrugNotesByProductIDAsync(POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDrugNotesByProductVIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDrugNotesByProductVID", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequestBody Body;
        
        public GetDrugNotesByProductVIDRequest() {
        }
        
        public GetDrugNotesByProductVIDRequest(POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDrugNotesByProductVIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VID;
        
        public GetDrugNotesByProductVIDRequestBody() {
        }
        
        public GetDrugNotesByProductVIDRequestBody(string VID) {
            this.VID = VID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDrugNotesByProductVIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDrugNotesByProductVIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_DrugNotes.GetDrugNotesByProductVIDResponseBody Body;
        
        public GetDrugNotesByProductVIDResponse() {
        }
        
        public GetDrugNotesByProductVIDResponse(POS_display.SR_DrugNotes.GetDrugNotesByProductVIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDrugNotesByProductVIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDrugNotesByProductVIDResult;
        
        public GetDrugNotesByProductVIDResponseBody() {
        }
        
        public GetDrugNotesByProductVIDResponseBody(string GetDrugNotesByProductVIDResult) {
            this.GetDrugNotesByProductVIDResult = GetDrugNotesByProductVIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDrugNotesByProductIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDrugNotesByProductID", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequestBody Body;
        
        public GetDrugNotesByProductIDRequest() {
        }
        
        public GetDrugNotesByProductIDRequest(POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDrugNotesByProductIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal ProductID;
        
        public GetDrugNotesByProductIDRequestBody() {
        }
        
        public GetDrugNotesByProductIDRequestBody(decimal ProductID) {
            this.ProductID = ProductID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDrugNotesByProductIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDrugNotesByProductIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_DrugNotes.GetDrugNotesByProductIDResponseBody Body;
        
        public GetDrugNotesByProductIDResponse() {
        }
        
        public GetDrugNotesByProductIDResponse(POS_display.SR_DrugNotes.GetDrugNotesByProductIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDrugNotesByProductIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDrugNotesByProductIDResult;
        
        public GetDrugNotesByProductIDResponseBody() {
        }
        
        public GetDrugNotesByProductIDResponseBody(string GetDrugNotesByProductIDResult) {
            this.GetDrugNotesByProductIDResult = GetDrugNotesByProductIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DrugNotesWSSoapChannel : POS_display.SR_DrugNotes.DrugNotesWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DrugNotesWSSoapClient : System.ServiceModel.ClientBase<POS_display.SR_DrugNotes.DrugNotesWSSoap>, POS_display.SR_DrugNotes.DrugNotesWSSoap {
        
        public DrugNotesWSSoapClient() {
        }
        
        public DrugNotesWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DrugNotesWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrugNotesWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DrugNotesWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_DrugNotes.GetDrugNotesByProductVIDResponse POS_display.SR_DrugNotes.DrugNotesWSSoap.GetDrugNotesByProductVID(POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequest request) {
            return base.Channel.GetDrugNotesByProductVID(request);
        }
        
        public string GetDrugNotesByProductVID(string VID) {
            POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequest inValue = new POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequest();
            inValue.Body = new POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequestBody();
            inValue.Body.VID = VID;
            POS_display.SR_DrugNotes.GetDrugNotesByProductVIDResponse retVal = ((POS_display.SR_DrugNotes.DrugNotesWSSoap)(this)).GetDrugNotesByProductVID(inValue);
            return retVal.Body.GetDrugNotesByProductVIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POS_display.SR_DrugNotes.GetDrugNotesByProductVIDResponse> POS_display.SR_DrugNotes.DrugNotesWSSoap.GetDrugNotesByProductVIDAsync(POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequest request) {
            return base.Channel.GetDrugNotesByProductVIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_DrugNotes.GetDrugNotesByProductVIDResponse> GetDrugNotesByProductVIDAsync(string VID) {
            POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequest inValue = new POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequest();
            inValue.Body = new POS_display.SR_DrugNotes.GetDrugNotesByProductVIDRequestBody();
            inValue.Body.VID = VID;
            return ((POS_display.SR_DrugNotes.DrugNotesWSSoap)(this)).GetDrugNotesByProductVIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_DrugNotes.GetDrugNotesByProductIDResponse POS_display.SR_DrugNotes.DrugNotesWSSoap.GetDrugNotesByProductID(POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequest request) {
            return base.Channel.GetDrugNotesByProductID(request);
        }
        
        public string GetDrugNotesByProductID(decimal ProductID) {
            POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequest inValue = new POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequest();
            inValue.Body = new POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequestBody();
            inValue.Body.ProductID = ProductID;
            POS_display.SR_DrugNotes.GetDrugNotesByProductIDResponse retVal = ((POS_display.SR_DrugNotes.DrugNotesWSSoap)(this)).GetDrugNotesByProductID(inValue);
            return retVal.Body.GetDrugNotesByProductIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POS_display.SR_DrugNotes.GetDrugNotesByProductIDResponse> POS_display.SR_DrugNotes.DrugNotesWSSoap.GetDrugNotesByProductIDAsync(POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequest request) {
            return base.Channel.GetDrugNotesByProductIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_DrugNotes.GetDrugNotesByProductIDResponse> GetDrugNotesByProductIDAsync(decimal ProductID) {
            POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequest inValue = new POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequest();
            inValue.Body = new POS_display.SR_DrugNotes.GetDrugNotesByProductIDRequestBody();
            inValue.Body.ProductID = ProductID;
            return ((POS_display.SR_DrugNotes.DrugNotesWSSoap)(this)).GetDrugNotesByProductIDAsync(inValue);
        }
    }
}
