//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_display.SR_TamroWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PhInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForecastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhName {
            get {
                return this.PhNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhNameField, value) != true)) {
                    this.PhNameField = value;
                    this.RaisePropertyChanged("PhName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BU {
            get {
                return this.BUField;
            }
            set {
                if ((object.ReferenceEquals(this.BUField, value) != true)) {
                    this.BUField = value;
                    this.RaisePropertyChanged("BU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AC {
            get {
                return this.ACField;
            }
            set {
                if ((object.ReferenceEquals(this.ACField, value) != true)) {
                    this.ACField = value;
                    this.RaisePropertyChanged("AC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Forecast {
            get {
                return this.ForecastField;
            }
            set {
                if ((object.ReferenceEquals(this.ForecastField, value) != true)) {
                    this.ForecastField = value;
                    this.RaisePropertyChanged("Forecast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BalticCategory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BalticCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cn3Field;
        
        private int c3_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cn2Field;
        
        private int c2_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cn1Field;
        
        private int c1_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cn0Field;
        
        private int c0_idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string cn3 {
            get {
                return this.cn3Field;
            }
            set {
                if ((object.ReferenceEquals(this.cn3Field, value) != true)) {
                    this.cn3Field = value;
                    this.RaisePropertyChanged("cn3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int c3_id {
            get {
                return this.c3_idField;
            }
            set {
                if ((this.c3_idField.Equals(value) != true)) {
                    this.c3_idField = value;
                    this.RaisePropertyChanged("c3_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cn2 {
            get {
                return this.cn2Field;
            }
            set {
                if ((object.ReferenceEquals(this.cn2Field, value) != true)) {
                    this.cn2Field = value;
                    this.RaisePropertyChanged("cn2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int c2_id {
            get {
                return this.c2_idField;
            }
            set {
                if ((this.c2_idField.Equals(value) != true)) {
                    this.c2_idField = value;
                    this.RaisePropertyChanged("c2_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string cn1 {
            get {
                return this.cn1Field;
            }
            set {
                if ((object.ReferenceEquals(this.cn1Field, value) != true)) {
                    this.cn1Field = value;
                    this.RaisePropertyChanged("cn1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int c1_id {
            get {
                return this.c1_idField;
            }
            set {
                if ((this.c1_idField.Equals(value) != true)) {
                    this.c1_idField = value;
                    this.RaisePropertyChanged("c1_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string cn0 {
            get {
                return this.cn0Field;
            }
            set {
                if ((object.ReferenceEquals(this.cn0Field, value) != true)) {
                    this.cn0Field = value;
                    this.RaisePropertyChanged("cn0");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int c0_id {
            get {
                return this.c0_idField;
            }
            set {
                if ((this.c0_idField.Equals(value) != true)) {
                    this.c0_idField = value;
                    this.RaisePropertyChanged("c0_id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_TamroWS.TamroWSSoap")]
    public interface TamroWSSoap {
        
        // CODEGEN: Generating message contract since element name pharmac_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPharmacyInfoForDate", ReplyAction="*")]
        POS_display.SR_TamroWS.GetPharmacyInfoForDateResponse GetPharmacyInfoForDate(POS_display.SR_TamroWS.GetPharmacyInfoForDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPharmacyInfoForDate", ReplyAction="*")]
        System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetPharmacyInfoForDateResponse> GetPharmacyInfoForDateAsync(POS_display.SR_TamroWS.GetPharmacyInfoForDateRequest request);
        
        // CODEGEN: Generating message contract since element name insurance from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInsuranceMaping", ReplyAction="*")]
        POS_display.SR_TamroWS.GetInsuranceMapingResponse GetInsuranceMaping(POS_display.SR_TamroWS.GetInsuranceMapingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInsuranceMaping", ReplyAction="*")]
        System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetInsuranceMapingResponse> GetInsuranceMapingAsync(POS_display.SR_TamroWS.GetInsuranceMapingRequest request);
        
        // CODEGEN: Generating message contract since element name GetBalticCategoryResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalticCategory", ReplyAction="*")]
        POS_display.SR_TamroWS.GetBalticCategoryResponse GetBalticCategory(POS_display.SR_TamroWS.GetBalticCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalticCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetBalticCategoryResponse> GetBalticCategoryAsync(POS_display.SR_TamroWS.GetBalticCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPharmacyInfoForDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPharmacyInfoForDate", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_TamroWS.GetPharmacyInfoForDateRequestBody Body;
        
        public GetPharmacyInfoForDateRequest() {
        }
        
        public GetPharmacyInfoForDateRequest(POS_display.SR_TamroWS.GetPharmacyInfoForDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPharmacyInfoForDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pharmac_id;
        
        public GetPharmacyInfoForDateRequestBody() {
        }
        
        public GetPharmacyInfoForDateRequestBody(string pharmac_id) {
            this.pharmac_id = pharmac_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPharmacyInfoForDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPharmacyInfoForDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_TamroWS.GetPharmacyInfoForDateResponseBody Body;
        
        public GetPharmacyInfoForDateResponse() {
        }
        
        public GetPharmacyInfoForDateResponse(POS_display.SR_TamroWS.GetPharmacyInfoForDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPharmacyInfoForDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POS_display.SR_TamroWS.PhInfo GetPharmacyInfoForDateResult;
        
        public GetPharmacyInfoForDateResponseBody() {
        }
        
        public GetPharmacyInfoForDateResponseBody(POS_display.SR_TamroWS.PhInfo GetPharmacyInfoForDateResult) {
            this.GetPharmacyInfoForDateResult = GetPharmacyInfoForDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInsuranceMapingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInsuranceMaping", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_TamroWS.GetInsuranceMapingRequestBody Body;
        
        public GetInsuranceMapingRequest() {
        }
        
        public GetInsuranceMapingRequest(POS_display.SR_TamroWS.GetInsuranceMapingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInsuranceMapingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string insurance;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal product_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal barcode_id;
        
        public GetInsuranceMapingRequestBody() {
        }
        
        public GetInsuranceMapingRequestBody(string insurance, decimal product_id, decimal barcode_id) {
            this.insurance = insurance;
            this.product_id = product_id;
            this.barcode_id = barcode_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInsuranceMapingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInsuranceMapingResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_TamroWS.GetInsuranceMapingResponseBody Body;
        
        public GetInsuranceMapingResponse() {
        }
        
        public GetInsuranceMapingResponse(POS_display.SR_TamroWS.GetInsuranceMapingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInsuranceMapingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInsuranceMapingResult;
        
        public GetInsuranceMapingResponseBody() {
        }
        
        public GetInsuranceMapingResponseBody(string GetInsuranceMapingResult) {
            this.GetInsuranceMapingResult = GetInsuranceMapingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalticCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalticCategory", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_TamroWS.GetBalticCategoryRequestBody Body;
        
        public GetBalticCategoryRequest() {
        }
        
        public GetBalticCategoryRequest(POS_display.SR_TamroWS.GetBalticCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalticCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal product_id;
        
        public GetBalticCategoryRequestBody() {
        }
        
        public GetBalticCategoryRequestBody(decimal product_id) {
            this.product_id = product_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBalticCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBalticCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_TamroWS.GetBalticCategoryResponseBody Body;
        
        public GetBalticCategoryResponse() {
        }
        
        public GetBalticCategoryResponse(POS_display.SR_TamroWS.GetBalticCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBalticCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POS_display.SR_TamroWS.BalticCategory GetBalticCategoryResult;
        
        public GetBalticCategoryResponseBody() {
        }
        
        public GetBalticCategoryResponseBody(POS_display.SR_TamroWS.BalticCategory GetBalticCategoryResult) {
            this.GetBalticCategoryResult = GetBalticCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TamroWSSoapChannel : POS_display.SR_TamroWS.TamroWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TamroWSSoapClient : System.ServiceModel.ClientBase<POS_display.SR_TamroWS.TamroWSSoap>, POS_display.SR_TamroWS.TamroWSSoap {
        
        public TamroWSSoapClient() {
        }
        
        public TamroWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TamroWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamroWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TamroWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_TamroWS.GetPharmacyInfoForDateResponse POS_display.SR_TamroWS.TamroWSSoap.GetPharmacyInfoForDate(POS_display.SR_TamroWS.GetPharmacyInfoForDateRequest request) {
            return base.Channel.GetPharmacyInfoForDate(request);
        }
        
        public POS_display.SR_TamroWS.PhInfo GetPharmacyInfoForDate(string pharmac_id) {
            POS_display.SR_TamroWS.GetPharmacyInfoForDateRequest inValue = new POS_display.SR_TamroWS.GetPharmacyInfoForDateRequest();
            inValue.Body = new POS_display.SR_TamroWS.GetPharmacyInfoForDateRequestBody();
            inValue.Body.pharmac_id = pharmac_id;
            POS_display.SR_TamroWS.GetPharmacyInfoForDateResponse retVal = ((POS_display.SR_TamroWS.TamroWSSoap)(this)).GetPharmacyInfoForDate(inValue);
            return retVal.Body.GetPharmacyInfoForDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetPharmacyInfoForDateResponse> POS_display.SR_TamroWS.TamroWSSoap.GetPharmacyInfoForDateAsync(POS_display.SR_TamroWS.GetPharmacyInfoForDateRequest request) {
            return base.Channel.GetPharmacyInfoForDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetPharmacyInfoForDateResponse> GetPharmacyInfoForDateAsync(string pharmac_id) {
            POS_display.SR_TamroWS.GetPharmacyInfoForDateRequest inValue = new POS_display.SR_TamroWS.GetPharmacyInfoForDateRequest();
            inValue.Body = new POS_display.SR_TamroWS.GetPharmacyInfoForDateRequestBody();
            inValue.Body.pharmac_id = pharmac_id;
            return ((POS_display.SR_TamroWS.TamroWSSoap)(this)).GetPharmacyInfoForDateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_TamroWS.GetInsuranceMapingResponse POS_display.SR_TamroWS.TamroWSSoap.GetInsuranceMaping(POS_display.SR_TamroWS.GetInsuranceMapingRequest request) {
            return base.Channel.GetInsuranceMaping(request);
        }
        
        public string GetInsuranceMaping(string insurance, decimal product_id, decimal barcode_id) {
            POS_display.SR_TamroWS.GetInsuranceMapingRequest inValue = new POS_display.SR_TamroWS.GetInsuranceMapingRequest();
            inValue.Body = new POS_display.SR_TamroWS.GetInsuranceMapingRequestBody();
            inValue.Body.insurance = insurance;
            inValue.Body.product_id = product_id;
            inValue.Body.barcode_id = barcode_id;
            POS_display.SR_TamroWS.GetInsuranceMapingResponse retVal = ((POS_display.SR_TamroWS.TamroWSSoap)(this)).GetInsuranceMaping(inValue);
            return retVal.Body.GetInsuranceMapingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetInsuranceMapingResponse> POS_display.SR_TamroWS.TamroWSSoap.GetInsuranceMapingAsync(POS_display.SR_TamroWS.GetInsuranceMapingRequest request) {
            return base.Channel.GetInsuranceMapingAsync(request);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetInsuranceMapingResponse> GetInsuranceMapingAsync(string insurance, decimal product_id, decimal barcode_id) {
            POS_display.SR_TamroWS.GetInsuranceMapingRequest inValue = new POS_display.SR_TamroWS.GetInsuranceMapingRequest();
            inValue.Body = new POS_display.SR_TamroWS.GetInsuranceMapingRequestBody();
            inValue.Body.insurance = insurance;
            inValue.Body.product_id = product_id;
            inValue.Body.barcode_id = barcode_id;
            return ((POS_display.SR_TamroWS.TamroWSSoap)(this)).GetInsuranceMapingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_TamroWS.GetBalticCategoryResponse POS_display.SR_TamroWS.TamroWSSoap.GetBalticCategory(POS_display.SR_TamroWS.GetBalticCategoryRequest request) {
            return base.Channel.GetBalticCategory(request);
        }
        
        public POS_display.SR_TamroWS.BalticCategory GetBalticCategory(decimal product_id) {
            POS_display.SR_TamroWS.GetBalticCategoryRequest inValue = new POS_display.SR_TamroWS.GetBalticCategoryRequest();
            inValue.Body = new POS_display.SR_TamroWS.GetBalticCategoryRequestBody();
            inValue.Body.product_id = product_id;
            POS_display.SR_TamroWS.GetBalticCategoryResponse retVal = ((POS_display.SR_TamroWS.TamroWSSoap)(this)).GetBalticCategory(inValue);
            return retVal.Body.GetBalticCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetBalticCategoryResponse> POS_display.SR_TamroWS.TamroWSSoap.GetBalticCategoryAsync(POS_display.SR_TamroWS.GetBalticCategoryRequest request) {
            return base.Channel.GetBalticCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<POS_display.SR_TamroWS.GetBalticCategoryResponse> GetBalticCategoryAsync(decimal product_id) {
            POS_display.SR_TamroWS.GetBalticCategoryRequest inValue = new POS_display.SR_TamroWS.GetBalticCategoryRequest();
            inValue.Body = new POS_display.SR_TamroWS.GetBalticCategoryRequestBody();
            inValue.Body.product_id = product_id;
            return ((POS_display.SR_TamroWS.TamroWSSoap)(this)).GetBalticCategoryAsync(inValue);
        }
    }
}
