//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_display.SR_InsuranceEPS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfXCardLimit", Namespace="http://tempuri.org/", ItemName="xCardLimit")]
    [System.SerializableAttribute()]
    public class ArrayOfXCardLimit : System.Collections.Generic.List<POS_display.SR_InsuranceEPS.xCardLimit> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="xCardLimit", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class xCardLimit : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xLimitCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xLimitNameField;
        
        private decimal xLimitBalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string xLimitCode {
            get {
                return this.xLimitCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.xLimitCodeField, value) != true)) {
                    this.xLimitCodeField = value;
                    this.RaisePropertyChanged("xLimitCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string xLimitName {
            get {
                return this.xLimitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.xLimitNameField, value) != true)) {
                    this.xLimitNameField = value;
                    this.RaisePropertyChanged("xLimitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal xLimitBalance {
            get {
                return this.xLimitBalanceField;
            }
            set {
                if ((this.xLimitBalanceField.Equals(value) != true)) {
                    this.xLimitBalanceField = value;
                    this.RaisePropertyChanged("xLimitBalance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POSpurchaseReceipt", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class POSpurchaseReceipt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private POS_display.SR_InsuranceEPS.POSpurchasedService[] purchasedServicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xAuthCodeField;
        
        private decimal finalAmountField;
        
        private decimal originalAmountField;
        
        private decimal compensatedAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public POS_display.SR_InsuranceEPS.POSpurchasedService[] purchasedServices {
            get {
                return this.purchasedServicesField;
            }
            set {
                if ((object.ReferenceEquals(this.purchasedServicesField, value) != true)) {
                    this.purchasedServicesField = value;
                    this.RaisePropertyChanged("purchasedServices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string xAuthCode {
            get {
                return this.xAuthCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.xAuthCodeField, value) != true)) {
                    this.xAuthCodeField = value;
                    this.RaisePropertyChanged("xAuthCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal finalAmount {
            get {
                return this.finalAmountField;
            }
            set {
                if ((this.finalAmountField.Equals(value) != true)) {
                    this.finalAmountField = value;
                    this.RaisePropertyChanged("finalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal originalAmount {
            get {
                return this.originalAmountField;
            }
            set {
                if ((this.originalAmountField.Equals(value) != true)) {
                    this.originalAmountField = value;
                    this.RaisePropertyChanged("originalAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal compensatedAmount {
            get {
                return this.compensatedAmountField;
            }
            set {
                if ((this.compensatedAmountField.Equals(value) != true)) {
                    this.compensatedAmountField = value;
                    this.RaisePropertyChanged("compensatedAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="POSpurchasedService", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class POSpurchasedService : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int recIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lCodeField;
        
        private decimal lVATRateField;
        
        private decimal lPriceField;
        
        private decimal lItemQuantityField;
        
        private decimal lTotalField;
        
        private byte lWasStateCompensationField;
        
        private decimal lStateCmpsnValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATCCodeField;
        
        private byte lHasReceiptField;
        
        private decimal xCompensatedValueField;
        
        private decimal xFinalTotalField;
        
        private int xCmpsnReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xCmpsnMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string xLimitNameField;
        
        private decimal xLimitBalanceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int recId {
            get {
                return this.recIdField;
            }
            set {
                if ((this.recIdField.Equals(value) != true)) {
                    this.recIdField = value;
                    this.RaisePropertyChanged("recId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lName {
            get {
                return this.lNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lNameField, value) != true)) {
                    this.lNameField = value;
                    this.RaisePropertyChanged("lName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lCode {
            get {
                return this.lCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.lCodeField, value) != true)) {
                    this.lCodeField = value;
                    this.RaisePropertyChanged("lCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal lVATRate {
            get {
                return this.lVATRateField;
            }
            set {
                if ((this.lVATRateField.Equals(value) != true)) {
                    this.lVATRateField = value;
                    this.RaisePropertyChanged("lVATRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal lPrice {
            get {
                return this.lPriceField;
            }
            set {
                if ((this.lPriceField.Equals(value) != true)) {
                    this.lPriceField = value;
                    this.RaisePropertyChanged("lPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal lItemQuantity {
            get {
                return this.lItemQuantityField;
            }
            set {
                if ((this.lItemQuantityField.Equals(value) != true)) {
                    this.lItemQuantityField = value;
                    this.RaisePropertyChanged("lItemQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public decimal lTotal {
            get {
                return this.lTotalField;
            }
            set {
                if ((this.lTotalField.Equals(value) != true)) {
                    this.lTotalField = value;
                    this.RaisePropertyChanged("lTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public byte lWasStateCompensation {
            get {
                return this.lWasStateCompensationField;
            }
            set {
                if ((this.lWasStateCompensationField.Equals(value) != true)) {
                    this.lWasStateCompensationField = value;
                    this.RaisePropertyChanged("lWasStateCompensation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public decimal lStateCmpsnValue {
            get {
                return this.lStateCmpsnValueField;
            }
            set {
                if ((this.lStateCmpsnValueField.Equals(value) != true)) {
                    this.lStateCmpsnValueField = value;
                    this.RaisePropertyChanged("lStateCmpsnValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ATCCode {
            get {
                return this.ATCCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ATCCodeField, value) != true)) {
                    this.ATCCodeField = value;
                    this.RaisePropertyChanged("ATCCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public byte lHasReceipt {
            get {
                return this.lHasReceiptField;
            }
            set {
                if ((this.lHasReceiptField.Equals(value) != true)) {
                    this.lHasReceiptField = value;
                    this.RaisePropertyChanged("lHasReceipt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public decimal xCompensatedValue {
            get {
                return this.xCompensatedValueField;
            }
            set {
                if ((this.xCompensatedValueField.Equals(value) != true)) {
                    this.xCompensatedValueField = value;
                    this.RaisePropertyChanged("xCompensatedValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public decimal xFinalTotal {
            get {
                return this.xFinalTotalField;
            }
            set {
                if ((this.xFinalTotalField.Equals(value) != true)) {
                    this.xFinalTotalField = value;
                    this.RaisePropertyChanged("xFinalTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public int xCmpsnReason {
            get {
                return this.xCmpsnReasonField;
            }
            set {
                if ((this.xCmpsnReasonField.Equals(value) != true)) {
                    this.xCmpsnReasonField = value;
                    this.RaisePropertyChanged("xCmpsnReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string xCmpsnMessage {
            get {
                return this.xCmpsnMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.xCmpsnMessageField, value) != true)) {
                    this.xCmpsnMessageField = value;
                    this.RaisePropertyChanged("xCmpsnMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string xLimitName {
            get {
                return this.xLimitNameField;
            }
            set {
                if ((object.ReferenceEquals(this.xLimitNameField, value) != true)) {
                    this.xLimitNameField = value;
                    this.RaisePropertyChanged("xLimitName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=16)]
        public decimal xLimitBalance {
            get {
                return this.xLimitBalanceField;
            }
            set {
                if ((this.xLimitBalanceField.Equals(value) != true)) {
                    this.xLimitBalanceField = value;
                    this.RaisePropertyChanged("xLimitBalance");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap")]
    public interface HealthInsuranceECRCompensationServiceSoap {
        
        // CODEGEN: Generating message contract since element name partnerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POSAuthorizeCard", ReplyAction="*")]
        POS_display.SR_InsuranceEPS.POSAuthorizeCardResponse POSAuthorizeCard(POS_display.SR_InsuranceEPS.POSAuthorizeCardRequest request);
        
        // CODEGEN: Generating message contract since element name partnerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POSGetCardBalance", ReplyAction="*")]
        POS_display.SR_InsuranceEPS.POSGetCardBalanceResponse POSGetCardBalance(POS_display.SR_InsuranceEPS.POSGetCardBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name partnerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POSCalculateCompensation", ReplyAction="*")]
        POS_display.SR_InsuranceEPS.POSCalculateCompensationResponse POSCalculateCompensation(POS_display.SR_InsuranceEPS.POSCalculateCompensationRequest request);
        
        // CODEGEN: Generating message contract since element name partnerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POSConfirmCompensation", ReplyAction="*")]
        POS_display.SR_InsuranceEPS.POSConfirmCompensationResponse POSConfirmCompensation(POS_display.SR_InsuranceEPS.POSConfirmCompensationRequest request);
        
        // CODEGEN: Generating message contract since element name partnerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POSCancelCompensation", ReplyAction="*")]
        POS_display.SR_InsuranceEPS.POSCancelCompensationResponse POSCancelCompensation(POS_display.SR_InsuranceEPS.POSCancelCompensationRequest request);
        
        // CODEGEN: Generating message contract since element name partnerId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/POSVoidCompensation", ReplyAction="*")]
        POS_display.SR_InsuranceEPS.POSVoidCompensationResponse POSVoidCompensation(POS_display.SR_InsuranceEPS.POSVoidCompensationRequest request);
        
        // CODEGEN: Generating message contract since element name pingId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Ping", ReplyAction="*")]
        POS_display.SR_InsuranceEPS.PingResponse Ping(POS_display.SR_InsuranceEPS.PingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSAuthorizeCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSAuthorizeCard", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSAuthorizeCardRequestBody Body;
        
        public POSAuthorizeCardRequest() {
        }
        
        public POSAuthorizeCardRequest(POS_display.SR_InsuranceEPS.POSAuthorizeCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSAuthorizeCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string posId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardNoHash;
        
        public POSAuthorizeCardRequestBody() {
        }
        
        public POSAuthorizeCardRequestBody(string partnerId, string posId, string cardNoHash) {
            this.partnerId = partnerId;
            this.posId = posId;
            this.cardNoHash = cardNoHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSAuthorizeCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSAuthorizeCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSAuthorizeCardResponseBody Body;
        
        public POSAuthorizeCardResponse() {
        }
        
        public POSAuthorizeCardResponse(POS_display.SR_InsuranceEPS.POSAuthorizeCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSAuthorizeCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardSessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int errCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errMsg;
        
        public POSAuthorizeCardResponseBody() {
        }
        
        public POSAuthorizeCardResponseBody(string cardSessionId, int errCode, string errMsg) {
            this.cardSessionId = cardSessionId;
            this.errCode = errCode;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSGetCardBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSGetCardBalance", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSGetCardBalanceRequestBody Body;
        
        public POSGetCardBalanceRequest() {
        }
        
        public POSGetCardBalanceRequest(POS_display.SR_InsuranceEPS.POSGetCardBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSGetCardBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string posId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardNoHash;
        
        public POSGetCardBalanceRequestBody() {
        }
        
        public POSGetCardBalanceRequestBody(string partnerId, string posId, string cardNoHash) {
            this.partnerId = partnerId;
            this.posId = posId;
            this.cardNoHash = cardNoHash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSGetCardBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSGetCardBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSGetCardBalanceResponseBody Body;
        
        public POSGetCardBalanceResponse() {
        }
        
        public POSGetCardBalanceResponse(POS_display.SR_InsuranceEPS.POSGetCardBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSGetCardBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POS_display.SR_InsuranceEPS.ArrayOfXCardLimit cardlimits;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int errCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errMsg;
        
        public POSGetCardBalanceResponseBody() {
        }
        
        public POSGetCardBalanceResponseBody(POS_display.SR_InsuranceEPS.ArrayOfXCardLimit cardlimits, int errCode, string errMsg) {
            this.cardlimits = cardlimits;
            this.errCode = errCode;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSCalculateCompensationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSCalculateCompensation", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSCalculateCompensationRequestBody Body;
        
        public POSCalculateCompensationRequest() {
        }
        
        public POSCalculateCompensationRequest(POS_display.SR_InsuranceEPS.POSCalculateCompensationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSCalculateCompensationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string posId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardSessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public POS_display.SR_InsuranceEPS.POSpurchaseReceipt currentReceipt;
        
        public POSCalculateCompensationRequestBody() {
        }
        
        public POSCalculateCompensationRequestBody(string partnerId, string posId, string cardSessionId, POS_display.SR_InsuranceEPS.POSpurchaseReceipt currentReceipt) {
            this.partnerId = partnerId;
            this.posId = posId;
            this.cardSessionId = cardSessionId;
            this.currentReceipt = currentReceipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSCalculateCompensationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSCalculateCompensationResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSCalculateCompensationResponseBody Body;
        
        public POSCalculateCompensationResponse() {
        }
        
        public POSCalculateCompensationResponse(POS_display.SR_InsuranceEPS.POSCalculateCompensationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSCalculateCompensationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POS_display.SR_InsuranceEPS.POSpurchaseReceipt currentReceipt;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int errCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errMsg;
        
        public POSCalculateCompensationResponseBody() {
        }
        
        public POSCalculateCompensationResponseBody(POS_display.SR_InsuranceEPS.POSpurchaseReceipt currentReceipt, int errCode, string errMsg) {
            this.currentReceipt = currentReceipt;
            this.errCode = errCode;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSConfirmCompensationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSConfirmCompensation", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSConfirmCompensationRequestBody Body;
        
        public POSConfirmCompensationRequest() {
        }
        
        public POSConfirmCompensationRequest(POS_display.SR_InsuranceEPS.POSConfirmCompensationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSConfirmCompensationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string posId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardSessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public POS_display.SR_InsuranceEPS.POSpurchaseReceipt currentReceipt;
        
        public POSConfirmCompensationRequestBody() {
        }
        
        public POSConfirmCompensationRequestBody(string partnerId, string posId, string cardSessionId, POS_display.SR_InsuranceEPS.POSpurchaseReceipt currentReceipt) {
            this.partnerId = partnerId;
            this.posId = posId;
            this.cardSessionId = cardSessionId;
            this.currentReceipt = currentReceipt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSConfirmCompensationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSConfirmCompensationResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSConfirmCompensationResponseBody Body;
        
        public POSConfirmCompensationResponse() {
        }
        
        public POSConfirmCompensationResponse(POS_display.SR_InsuranceEPS.POSConfirmCompensationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSConfirmCompensationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string compensationAuthNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int errCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string errMsg;
        
        public POSConfirmCompensationResponseBody() {
        }
        
        public POSConfirmCompensationResponseBody(string compensationAuthNo, int errCode, string errMsg) {
            this.compensationAuthNo = compensationAuthNo;
            this.errCode = errCode;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSCancelCompensationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSCancelCompensation", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSCancelCompensationRequestBody Body;
        
        public POSCancelCompensationRequest() {
        }
        
        public POSCancelCompensationRequest(POS_display.SR_InsuranceEPS.POSCancelCompensationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSCancelCompensationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string posId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardSessionId;
        
        public POSCancelCompensationRequestBody() {
        }
        
        public POSCancelCompensationRequestBody(string partnerId, string posId, string cardSessionId) {
            this.partnerId = partnerId;
            this.posId = posId;
            this.cardSessionId = cardSessionId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSCancelCompensationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSCancelCompensationResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSCancelCompensationResponseBody Body;
        
        public POSCancelCompensationResponse() {
        }
        
        public POSCancelCompensationResponse(POS_display.SR_InsuranceEPS.POSCancelCompensationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSCancelCompensationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int errCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMsg;
        
        public POSCancelCompensationResponseBody() {
        }
        
        public POSCancelCompensationResponseBody(int errCode, string errMsg) {
            this.errCode = errCode;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSVoidCompensationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSVoidCompensation", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSVoidCompensationRequestBody Body;
        
        public POSVoidCompensationRequest() {
        }
        
        public POSVoidCompensationRequest(POS_display.SR_InsuranceEPS.POSVoidCompensationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSVoidCompensationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string partnerId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string posId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string cardSessionId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string compensationAuthNo;
        
        public POSVoidCompensationRequestBody() {
        }
        
        public POSVoidCompensationRequestBody(string partnerId, string posId, string cardSessionId, string compensationAuthNo) {
            this.partnerId = partnerId;
            this.posId = posId;
            this.cardSessionId = cardSessionId;
            this.compensationAuthNo = compensationAuthNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class POSVoidCompensationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="POSVoidCompensationResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.POSVoidCompensationResponseBody Body;
        
        public POSVoidCompensationResponse() {
        }
        
        public POSVoidCompensationResponse(POS_display.SR_InsuranceEPS.POSVoidCompensationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class POSVoidCompensationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int errCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string errMsg;
        
        public POSVoidCompensationResponseBody() {
        }
        
        public POSVoidCompensationResponseBody(int errCode, string errMsg) {
            this.errCode = errCode;
            this.errMsg = errMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Ping", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.PingRequestBody Body;
        
        public PingRequest() {
        }
        
        public PingRequest(POS_display.SR_InsuranceEPS.PingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pingId;
        
        public PingRequestBody() {
        }
        
        public PingRequestBody(string pingId) {
            this.pingId = pingId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PingResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_InsuranceEPS.PingResponseBody Body;
        
        public PingResponse() {
        }
        
        public PingResponse(POS_display.SR_InsuranceEPS.PingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime localTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long databaseRequestDuration;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int errCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string errMsg;
        
        public PingResponseBody() {
        }
        
        public PingResponseBody(System.DateTime localTime, long databaseRequestDuration, int errCode, string errMsg) {
            this.localTime = localTime;
            this.databaseRequestDuration = databaseRequestDuration;
            this.errCode = errCode;
            this.errMsg = errMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HealthInsuranceECRCompensationServiceSoapChannel : POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HealthInsuranceECRCompensationServiceSoapClient : System.ServiceModel.ClientBase<POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap>, POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap {
        
        public HealthInsuranceECRCompensationServiceSoapClient() {
        }
        
        public HealthInsuranceECRCompensationServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HealthInsuranceECRCompensationServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HealthInsuranceECRCompensationServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HealthInsuranceECRCompensationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_InsuranceEPS.POSAuthorizeCardResponse POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap.POSAuthorizeCard(POS_display.SR_InsuranceEPS.POSAuthorizeCardRequest request) {
            return base.Channel.POSAuthorizeCard(request);
        }
        
        public string POSAuthorizeCard(string partnerId, string posId, string cardNoHash, out int errCode, out string errMsg) {
            POS_display.SR_InsuranceEPS.POSAuthorizeCardRequest inValue = new POS_display.SR_InsuranceEPS.POSAuthorizeCardRequest();
            inValue.Body = new POS_display.SR_InsuranceEPS.POSAuthorizeCardRequestBody();
            inValue.Body.partnerId = partnerId;
            inValue.Body.posId = posId;
            inValue.Body.cardNoHash = cardNoHash;
            POS_display.SR_InsuranceEPS.POSAuthorizeCardResponse retVal = ((POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap)(this)).POSAuthorizeCard(inValue);
            errCode = retVal.Body.errCode;
            errMsg = retVal.Body.errMsg;
            return retVal.Body.cardSessionId;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_InsuranceEPS.POSGetCardBalanceResponse POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap.POSGetCardBalance(POS_display.SR_InsuranceEPS.POSGetCardBalanceRequest request) {
            return base.Channel.POSGetCardBalance(request);
        }
        
        public POS_display.SR_InsuranceEPS.ArrayOfXCardLimit POSGetCardBalance(string partnerId, string posId, string cardNoHash, out int errCode, out string errMsg) {
            POS_display.SR_InsuranceEPS.POSGetCardBalanceRequest inValue = new POS_display.SR_InsuranceEPS.POSGetCardBalanceRequest();
            inValue.Body = new POS_display.SR_InsuranceEPS.POSGetCardBalanceRequestBody();
            inValue.Body.partnerId = partnerId;
            inValue.Body.posId = posId;
            inValue.Body.cardNoHash = cardNoHash;
            POS_display.SR_InsuranceEPS.POSGetCardBalanceResponse retVal = ((POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap)(this)).POSGetCardBalance(inValue);
            errCode = retVal.Body.errCode;
            errMsg = retVal.Body.errMsg;
            return retVal.Body.cardlimits;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_InsuranceEPS.POSCalculateCompensationResponse POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap.POSCalculateCompensation(POS_display.SR_InsuranceEPS.POSCalculateCompensationRequest request) {
            return base.Channel.POSCalculateCompensation(request);
        }
        
        public int POSCalculateCompensation(string partnerId, string posId, string cardSessionId, ref POS_display.SR_InsuranceEPS.POSpurchaseReceipt currentReceipt, out string errMsg) {
            POS_display.SR_InsuranceEPS.POSCalculateCompensationRequest inValue = new POS_display.SR_InsuranceEPS.POSCalculateCompensationRequest();
            inValue.Body = new POS_display.SR_InsuranceEPS.POSCalculateCompensationRequestBody();
            inValue.Body.partnerId = partnerId;
            inValue.Body.posId = posId;
            inValue.Body.cardSessionId = cardSessionId;
            inValue.Body.currentReceipt = currentReceipt;
            POS_display.SR_InsuranceEPS.POSCalculateCompensationResponse retVal = ((POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap)(this)).POSCalculateCompensation(inValue);
            currentReceipt = retVal.Body.currentReceipt;
            errMsg = retVal.Body.errMsg;
            return retVal.Body.errCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_InsuranceEPS.POSConfirmCompensationResponse POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap.POSConfirmCompensation(POS_display.SR_InsuranceEPS.POSConfirmCompensationRequest request) {
            return base.Channel.POSConfirmCompensation(request);
        }
        
        public string POSConfirmCompensation(string partnerId, string posId, string cardSessionId, POS_display.SR_InsuranceEPS.POSpurchaseReceipt currentReceipt, out int errCode, out string errMsg) {
            POS_display.SR_InsuranceEPS.POSConfirmCompensationRequest inValue = new POS_display.SR_InsuranceEPS.POSConfirmCompensationRequest();
            inValue.Body = new POS_display.SR_InsuranceEPS.POSConfirmCompensationRequestBody();
            inValue.Body.partnerId = partnerId;
            inValue.Body.posId = posId;
            inValue.Body.cardSessionId = cardSessionId;
            inValue.Body.currentReceipt = currentReceipt;
            POS_display.SR_InsuranceEPS.POSConfirmCompensationResponse retVal = ((POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap)(this)).POSConfirmCompensation(inValue);
            errCode = retVal.Body.errCode;
            errMsg = retVal.Body.errMsg;
            return retVal.Body.compensationAuthNo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_InsuranceEPS.POSCancelCompensationResponse POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap.POSCancelCompensation(POS_display.SR_InsuranceEPS.POSCancelCompensationRequest request) {
            return base.Channel.POSCancelCompensation(request);
        }
        
        public int POSCancelCompensation(string partnerId, string posId, string cardSessionId, out string errMsg) {
            POS_display.SR_InsuranceEPS.POSCancelCompensationRequest inValue = new POS_display.SR_InsuranceEPS.POSCancelCompensationRequest();
            inValue.Body = new POS_display.SR_InsuranceEPS.POSCancelCompensationRequestBody();
            inValue.Body.partnerId = partnerId;
            inValue.Body.posId = posId;
            inValue.Body.cardSessionId = cardSessionId;
            POS_display.SR_InsuranceEPS.POSCancelCompensationResponse retVal = ((POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap)(this)).POSCancelCompensation(inValue);
            errMsg = retVal.Body.errMsg;
            return retVal.Body.errCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_InsuranceEPS.POSVoidCompensationResponse POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap.POSVoidCompensation(POS_display.SR_InsuranceEPS.POSVoidCompensationRequest request) {
            return base.Channel.POSVoidCompensation(request);
        }
        
        public int POSVoidCompensation(string partnerId, string posId, string cardSessionId, string compensationAuthNo, out string errMsg) {
            POS_display.SR_InsuranceEPS.POSVoidCompensationRequest inValue = new POS_display.SR_InsuranceEPS.POSVoidCompensationRequest();
            inValue.Body = new POS_display.SR_InsuranceEPS.POSVoidCompensationRequestBody();
            inValue.Body.partnerId = partnerId;
            inValue.Body.posId = posId;
            inValue.Body.cardSessionId = cardSessionId;
            inValue.Body.compensationAuthNo = compensationAuthNo;
            POS_display.SR_InsuranceEPS.POSVoidCompensationResponse retVal = ((POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap)(this)).POSVoidCompensation(inValue);
            errMsg = retVal.Body.errMsg;
            return retVal.Body.errCode;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_InsuranceEPS.PingResponse POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap.Ping(POS_display.SR_InsuranceEPS.PingRequest request) {
            return base.Channel.Ping(request);
        }
        
        public System.DateTime Ping(string pingId, out long databaseRequestDuration, out int errCode, out string errMsg) {
            POS_display.SR_InsuranceEPS.PingRequest inValue = new POS_display.SR_InsuranceEPS.PingRequest();
            inValue.Body = new POS_display.SR_InsuranceEPS.PingRequestBody();
            inValue.Body.pingId = pingId;
            POS_display.SR_InsuranceEPS.PingResponse retVal = ((POS_display.SR_InsuranceEPS.HealthInsuranceECRCompensationServiceSoap)(this)).Ping(inValue);
            databaseRequestDuration = retVal.Body.databaseRequestDuration;
            errCode = retVal.Body.errCode;
            errMsg = retVal.Body.errMsg;
            return retVal.Body.localTime;
        }
    }
}
