//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS_display.SR_PharmacyInfo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhInfo", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PhInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ForecastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhName {
            get {
                return this.PhNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PhNameField, value) != true)) {
                    this.PhNameField = value;
                    this.RaisePropertyChanged("PhName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BU {
            get {
                return this.BUField;
            }
            set {
                if ((object.ReferenceEquals(this.BUField, value) != true)) {
                    this.BUField = value;
                    this.RaisePropertyChanged("BU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AC {
            get {
                return this.ACField;
            }
            set {
                if ((object.ReferenceEquals(this.ACField, value) != true)) {
                    this.ACField = value;
                    this.RaisePropertyChanged("AC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Forecast {
            get {
                return this.ForecastField;
            }
            set {
                if ((object.ReferenceEquals(this.ForecastField, value) != true)) {
                    this.ForecastField = value;
                    this.RaisePropertyChanged("Forecast");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SR_PharmacyInfo.PharmacyInfoSoap")]
    public interface PharmacyInfoSoap {
        
        // CODEGEN: Generating message contract since element name Phs_id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPharmacyInfoForDate", ReplyAction="*")]
        POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateResponse GetPharmacyInfoForDate(POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPharmacyInfoForDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPharmacyInfoForDate", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateRequestBody Body;
        
        public GetPharmacyInfoForDateRequest() {
        }
        
        public GetPharmacyInfoForDateRequest(POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPharmacyInfoForDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Phs_id;
        
        public GetPharmacyInfoForDateRequestBody() {
        }
        
        public GetPharmacyInfoForDateRequestBody(string Phs_id) {
            this.Phs_id = Phs_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPharmacyInfoForDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPharmacyInfoForDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateResponseBody Body;
        
        public GetPharmacyInfoForDateResponse() {
        }
        
        public GetPharmacyInfoForDateResponse(POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPharmacyInfoForDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public POS_display.SR_PharmacyInfo.PhInfo GetPharmacyInfoForDateResult;
        
        public GetPharmacyInfoForDateResponseBody() {
        }
        
        public GetPharmacyInfoForDateResponseBody(POS_display.SR_PharmacyInfo.PhInfo GetPharmacyInfoForDateResult) {
            this.GetPharmacyInfoForDateResult = GetPharmacyInfoForDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PharmacyInfoSoapChannel : POS_display.SR_PharmacyInfo.PharmacyInfoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PharmacyInfoSoapClient : System.ServiceModel.ClientBase<POS_display.SR_PharmacyInfo.PharmacyInfoSoap>, POS_display.SR_PharmacyInfo.PharmacyInfoSoap {
        
        public PharmacyInfoSoapClient() {
        }
        
        public PharmacyInfoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PharmacyInfoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PharmacyInfoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PharmacyInfoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateResponse POS_display.SR_PharmacyInfo.PharmacyInfoSoap.GetPharmacyInfoForDate(POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateRequest request) {
            return base.Channel.GetPharmacyInfoForDate(request);
        }
        
        public POS_display.SR_PharmacyInfo.PhInfo GetPharmacyInfoForDate(string Phs_id) {
            POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateRequest inValue = new POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateRequest();
            inValue.Body = new POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateRequestBody();
            inValue.Body.Phs_id = Phs_id;
            POS_display.SR_PharmacyInfo.GetPharmacyInfoForDateResponse retVal = ((POS_display.SR_PharmacyInfo.PharmacyInfoSoap)(this)).GetPharmacyInfoForDate(inValue);
            return retVal.Body.GetPharmacyInfoForDateResult;
        }
    }
}
